export const metadata = {
    title: 'GitHub Status',
    description: 'Generated by create next app',
  }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
  